### ISSUE TITLE
Is this a working wrapper?

### ISSUE THREAD

**Issue by spupett** [appfeel/angular-elevate-zoom#1]
I'm trying to use this and it's not working for me.  

My HTML is as follows

```
<div ng-controller="zoomCtrl">
    <img id="blah" class="img-responsive" ez-zoom ng-src="{{image}}" ez-zoom-config="{cursor: crosshair}" ez-zoom-image="{{imageZoom}}">
</div>
Bottom Line
```

My zoomCtrl is as follows

```
angular.module('myApp', [])
    .controller('zoomCtrl', function($scope) {
            $scope.image = 'img/smallImage3.png'
            $scope.imageZoom = 'img/largeImage3.jpg'
    });
```

All I'm getting at this point is the zoomed out image.  I'm just wondering if I'm using it wrong or if this is still a work in progress.

**Comment by appfeel** [comment]
That should work, did you added the dependency?

``` javascript
angular.module('myApp', ['angular-elevate-zoom']);
```

Anyway I've seen that maybe it should be mentioned in the documentation... :)
