### ISSUE TITLE
zoomtype: Inner problem

### ISSUE THREAD

**Issue by noushad-pp** [appfeel/angular-elevate-zoom#2]
this is my wrapper
 `<img class="col-md-12 noPadding prodDetImg img-responsive" id="zoomImg" ng-src="{{currentImage}}" ez-zoom ez-zoom-image="{{currentImage}}" ez-zoom-config="{'zoomType': 'inner', 'cursor': 'crosshair', 'easing' : true}""/>`

My inner zoom works fine but once zoomed in the image remains zoomed in. On mousleave the zoomcontainer still remains.
If we changed the image, each time a new zoom container is created which is also zoomed in. why is it so?

**Comment by noushad-pp** [comment]
fixed issue.

**Comment by nkomikawa** [comment]
How did you fixed?
Can you post your controller, please? I am confused with images and catalog.
Thanks
