### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by nkomikawa** [appfeel/angular-elevate-zoom#3]
Can you post a demo, please?
I tried, the page show the image but nothing happens when the mouse is over.
Thanks.

**Comment by zearaez** [comment]
Here is the demo [plunker](http://plnkr.co/edit/8Umdvr1aGq7HjV6Enoxv?p=preview)

**Comment by miqmago** [comment]
Thanks @zearaez, i've modified it with the directives provided by this plugin which allows to specify configuration object: http://plnkr.co/edit/97Hqkf1EIdN1s5lZhlQo?p=preview
